[package]
name = "sdkwork-api-mcp-assembly"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Generated API assembly for sdkwork-mcp application HTTP plane."

[lib]
name = "sdkwork_api_mcp_assembly"
path = "src/lib.rs"

[dependencies]
axum.workspace = true
tokio.workspace = true
sdkwork-web-bootstrap.workspace = true
sdkwork-web-core.workspace = true
sqlx.workspace = true
sdkwork-database-sqlx.workspace = true
sdkwork-intelligence-mcp-repository-sqlx = { workspace = true }
sdkwork-intelligence-mcp-service = { workspace = true }
sdkwork_mcp_database_host.workspace = true
sdkwork-routes-mcp-shared.workspace = true
sdkwork_routes_mcp_app_api = { workspace = true }
sdkwork_routes_mcp_backend_api = { workspace = true }
